version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: 1111
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - today_hymn_db:/var/lib/mysql

  server:
    image: today-hymn-server
    container_name: server
    build: 
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command: 
      - sh 
      - "init.sh"
    
    
volumes:
  today_hymn_db:
    driver: local
